alter table if exists webdb.games drop constraint if exists FKgne945jcsifcvy6s9dy44ueit;
alter table if exists webdb.games drop constraint if exists FKmhtkuklj000hu8rp0k7wdng5k;
alter table if exists webdb.matches drop constraint if exists FKeeniokyjgo5k6rmhjujatn27i;
alter table if exists webdb.matches drop constraint if exists FKn66swy9if3qemrk5407f81hc5;
alter table if exists webdb.matches_teams drop constraint if exists FK3wddsuk7fqdyg8c25hvvn7ymj;
alter table if exists webdb.matches_teams drop constraint if exists FKjmskbx5liuu6g99itdrexxojt;
alter table if exists webdb.sport_disciplines drop constraint if exists FKjrwf8i3l2kytik3i69mlms4wc;
alter table if exists webdb.teams drop constraint if exists FKo5qehaxeuk4i5bxwpf20dvcws;
alter table if exists webdb.teams_people drop constraint if exists FKnfv56vomq15knrvdopdrk3c4x;
alter table if exists webdb.teams_people drop constraint if exists FK9b0pgwid2wpogutyjlan3tcpr;
alter table if exists webdb.tournament_judges drop constraint if exists FKc2qxbugjcc0wsdk5c27kgwlnc;
alter table if exists webdb.tournament_judges drop constraint if exists FKi3ga0q1v18vd0btj139udk09n;
alter table if exists webdb.tournaments drop constraint if exists FKrobw7525m6byh2cd9l7k0flom;
alter table if exists webdb.tournaments drop constraint if exists FKk7tnshm8iafo9skfk6tkjklft;
alter table if exists webdb.user_roles drop constraint if exists FKhfh9dx7w3ubf1co1vdev94g3f;

drop table if exists webdb.games cascade;
drop table if exists webdb.matches cascade;
drop table if exists webdb.matches_teams cascade;
drop table if exists webdb.people cascade;
drop table if exists webdb.sport_disciplines cascade;
drop table if exists webdb.sport_kinds cascade;
drop table if exists webdb.teams cascade;
drop table if exists webdb.teams_people cascade;
drop table if exists webdb.tournament_judges cascade;
drop table if exists webdb.tournaments cascade;
drop table if exists webdb.user_roles cascade;
drop table if exists webdb.users cascade;

create table webdb.games (id int4 generated always as identity, first_team_score int2, second_team_score int2, match_id int4 not null, winner_team_id int4, primary key (id));
create table webdb.matches (id int4 generated always as identity, first_team_score int2, second_team_score int2, tournament_id int4 not null, winner_team_id int4, primary key (id));
create table webdb.matches_teams (match_id int4 not null, team_id int4 not null, primary key (match_id, team_id));
create table webdb.people (id int4 generated always as identity, birth_date date not null, city varchar(35), gender int2, name varchar(30) not null, patronymic varchar(30), surname varchar(30) not null, primary key (id));
create table webdb.sport_disciplines (id int4 generated always as identity, code varchar(11) not null, name varchar(50) not null, sport_kind_id int4 not null, primary key (id));
create table webdb.sport_kinds (id int4 generated always as identity, code varchar(11) not null, name varchar(50) not null, primary key (id));
create table webdb.teams (id int4 generated always as identity, name varchar(30) not null, tournament_id int4 not null, primary key (id));
create table webdb.teams_people (team_id int4 not null, human_id int4 not null, primary key (team_id, human_id));
create table webdb.tournament_judges (tournament_id int4 not null, human_id int4 not null, primary key (tournament_id, human_id));
create table webdb.tournaments (id int4 generated always as identity, age_group varchar(20) not null, category varchar(10) not null, city varchar(35) not null, date_from date not null, date_till date not null, format varchar(20) not null, gender int2, name varchar(30) not null, team_amount int2 not null, team_capacity int2 not null, tournament_class varchar(10) not null, sport_discipline_id int4 not null, winner_team_id int4, primary key (id));
create table webdb.user_roles (user_id int4 not null, roles varchar(255));
create table webdb.users (id int4 generated always as identity, password varchar(100) not null, username varchar(30) not null, primary key (id));

alter table if exists webdb.games add constraint FKgne945jcsifcvy6s9dy44ueit foreign key (match_id) references webdb.matches;
alter table if exists webdb.games add constraint FKmhtkuklj000hu8rp0k7wdng5k foreign key (winner_team_id) references webdb.teams;
alter table if exists webdb.matches add constraint FKeeniokyjgo5k6rmhjujatn27i foreign key (tournament_id) references webdb.tournaments;
alter table if exists webdb.matches add constraint FKn66swy9if3qemrk5407f81hc5 foreign key (winner_team_id) references webdb.teams;
alter table if exists webdb.matches_teams add constraint FK3wddsuk7fqdyg8c25hvvn7ymj foreign key (team_id) references webdb.teams;
alter table if exists webdb.matches_teams add constraint FKjmskbx5liuu6g99itdrexxojt foreign key (match_id) references webdb.matches;
alter table if exists webdb.sport_disciplines add constraint FKjrwf8i3l2kytik3i69mlms4wc foreign key (sport_kind_id) references webdb.sport_kinds;
alter table if exists webdb.teams add constraint FKo5qehaxeuk4i5bxwpf20dvcws foreign key (tournament_id) references webdb.tournaments;
alter table if exists webdb.teams_people add constraint FKnfv56vomq15knrvdopdrk3c4x foreign key (human_id) references webdb.people;
alter table if exists webdb.teams_people add constraint FK9b0pgwid2wpogutyjlan3tcpr foreign key (team_id) references webdb.teams;
alter table if exists webdb.tournament_judges add constraint FKc2qxbugjcc0wsdk5c27kgwlnc foreign key (human_id) references webdb.people;
alter table if exists webdb.tournament_judges add constraint FKi3ga0q1v18vd0btj139udk09n foreign key (tournament_id) references webdb.tournaments;
alter table if exists webdb.tournaments add constraint FKrobw7525m6byh2cd9l7k0flom foreign key (sport_discipline_id) references webdb.sport_disciplines;
alter table if exists webdb.tournaments add constraint FKk7tnshm8iafo9skfk6tkjklft foreign key (winner_team_id) references webdb.teams;
alter table if exists webdb.user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references webdb.users;